### ISSUE TITLE
去除一些不合理的设计

### ISSUE THREAD

**Issue by OasisAkari** [Teahouse-Studios/bot#10]
![image](https://user-images.githubusercontent.com/31803608/115397985-3f9bf680-a219-11eb-92d4-5a89a2d7770d.png)

如图，约0%的人选择了关闭wiki命令的自动渲染infobox的选项。

目前bot内部设计了三套模块方案：

1. 群组内模块
2. 个人关闭模块（同时控制在群组内的行为）
3. 好友模块

考虑到即将尝试适配tg和dc，为了降低开发复杂度，将会取消2方案。（因为没有人会选择关闭某特定功能，且~enable self 命令需要同时兼顾2和3方案，增加开发的迷惑性。）

**Comment by XxLittleCxX** [comment]
不要适配了 来koishi重写吧

**Comment by OasisAkari** [comment]
> 不要适配了 来koishi重写吧

我不要我不要我不要我不要我不要我不要我不要我不要我不要（大声）

**Comment by XxLittleCxX** [comment]
@Dragon-Fish 来

**Comment by XxLittleCxX** [comment]
什么时候做`koishipy`
