### ISSUE TITLE
新的命令解析

### ISSUE THREAD

**Issue by OasisAkari** [Teahouse-Studios/bot#12]

**Comment by XxLittleCxX** [comment]
koishi

**Comment by OasisAkari** [comment]
会基于argparse模块上开发，原因是 ~~**我要摸鱼（超大声）**~~ 现有技术力不足以再开发一个新的轮子

**Comment by OasisAkari** [comment]
目前缺陷：
语法解析只能到第二层，且第二层内不可出现可选参数

因为试图写生成语法树不知如何下手

**Comment by OasisAkari** [comment]
![image](https://user-images.githubusercontent.com/31803608/126190167-42ec798b-b6dd-4ecd-87e3-965ce6356a2c.png)

在装饰器内填写help_doc后，上游解析器就会根据help_doc内写入的信息生成一个解析后消息的dict（存储于message['parsed_msg']），上文模拟运行示例如下：

![image](https://user-images.githubusercontent.com/31803608/126190974-57d61010-eb8d-477a-b128-8e2784418598.png)

help_doc可以是 str, list 或者 tuple

语法见：https://github.com/jazzband/docopt-ng#usage-pattern-format

（解析器会自动生成Usage pattern，直接看语法部分即可）

追加语法：
{} - 填入的内容用来指明该条命令的详细信息

**Comment by OasisAkari** [comment]
修改后的docopt会尝试在命令出现多余参数时自动合并其至上一个参数再次解析，用于优化使用体验

如果出现空格的参数不在消息的末尾，则需给其加上引号
例如：
语法：~aaa <args1> <args2>
不加引号：~aaa bbb ccc ddd # {'<args1>': 'bbb', '<args2>': 'ccc ddd'}
加上引号：~aaa "bbb ccc" ddd # {'<args1>': 'bbb ccc', '<args2>': 'ddd'}

**Comment by OasisAkari** [comment]
()和|在写help_doc的时候尽量少用或者不用~~那你还用~~，多写几条用tuple或者list展示时更直观，也不会影响命令解析

**Comment by OasisAkari** [comment]
> ()和|在写help_doc的时候尽量少用或者不用~~那你还用~~，多写几条用tuple或者list传入展示时更直观，也不会影响命令解析

**Comment by OasisAkari** [comment]
todo: 重新修改docopt-ng使参数合并更合理

**Comment by Dianliang233** [comment]
> 修改后的docopt会尝试在命令出现多余参数时自动合并其至上一个参数再次解析，用于优化使用体验
> 
> 如果出现空格的参数不在消息的末尾，则需给其加上引号
> 例如：
> 
> ```
> 语法：~aaa <args1> <args2>
> 不加引号：~aaa bbb ccc ddd # {'<args1>': 'bbb', '<args2>': 'ccc ddd'}
> 加上引号：~aaa "bbb ccc" ddd # {'<args1>': 'bbb ccc', '<args2>': 'ddd'}
> ```

鉴于中文语境，需要把`“` `”`两个蝌蚪引号先转换成`"`
