### ISSUE TITLE
申请小业的粉丝群加入

### ISSUE THREAD

**Issue by lakejason0** [Teahouse-Studios/bot#120]
**我已阅读并同意小可 [服务条款](https://bot.teahou.se/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahou.se/privacy)、问谛居 [用户协议](https://doc.wd-ljt.com/policy/user/) 和 [隐私政策](https://doc.wd-ljt.com/policy/privacy/)**

**申请QQ号：**974932325

**申请QQ群：**1032978105

**备注：**

**Comment by OasisAkari** [comment]
这谁啊，活久见
