### ISSUE TITLE
修复restart命令

### ISSUE THREAD

**Issue by OasisAkari** [Teahouse-Studios/bot#121]

**Comment by OasisAkari** [comment]
os.execl会导致aiocqhttp的websocket无法正常断开，暂时无解决方案。

暂时禁用此系列命令。

**Comment by Dianliang233** [comment]
what about `sys.exit()`

**Comment by OasisAkari** [comment]
可能可以在 https://github.com/Teahouse-Studios/bot/blob/master/bot.py 写个捕获某个退出状态码的功能，捕获到就kill全部子进程然后重新启动

**Comment by OasisAkari** [comment]
windows和linux环境下的行为不一样，哈哈，哈哈，哈
呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜呜明天再修了

**Comment by lakejason0** [comment]
抱抱
