### ISSUE TITLE
736444497

### ISSUE THREAD

**Issue by lanxuanfeng88** [Teahouse-Studios/bot#122]
**我已阅读并同意小可 [服务条款](https://bot.teahou.se/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahou.se/privacy)、问谛居 [用户协议](https://doc.wd-ljt.com/policy/user/) 和 [隐私政策](https://doc.wd-ljt.com/policy/privacy/)**

**申请QQ号：**

**申请QQ群：**

**备注：**

**Comment by OasisAkari** [comment]
请按格式填写issue 否则不予处理
