### ISSUE TITLE
希望server模块新增选项以选择是否90s后撤回

### ISSUE THREAD

**Issue by z0z0r4** [Teahouse-Studios/bot#127]
请求如标题，原因是撤回后导致群友先来后到，没看见前一个人查询，结果相继查询…
如图
![7624b3de103efb94](https://user-images.githubusercontent.com/78744121/142749594-2cabb3be-b278-4c48-8964-b32dda6a060b.jpg)
如果可以选择不撤回的话，就没这种事了

**Comment by z0z0r4** [comment]
一时想法，另有不足之处请指出awa

**Comment by OasisAkari** [comment]
晚上会加个参数

**Comment by z0z0r4** [comment]
另外，如果给bot管理员的话，是不是也可以让它顺便把成员发的~s ip:port也撤回了
也是麻了，一个群都是~s

**Comment by z0z0r4** [comment]
另外是不是可以给bot加管理，让它把发出的~ s等等也撤回了
一个群都是~ s 麻了

**Comment by z0z0r4** [comment]
谢谢 :-)

**Comment by OasisAkari** [comment]
暂时没有这样的逻辑

**Comment by OasisAkari** [comment]
> 另外是不是可以给bot加管理，让它把发出的~ s等等也撤回了
> 一个群都是~ s 麻了

暂时没有这样的逻辑

**Comment by Dianliang233** [comment]
建议：取消server自动撤回

**Comment by OasisAkari** [comment]
> 建议：取消server自动撤回

这个当初是littlec加的

**Comment by OasisAkari** [comment]
:rina:

**Comment by lakejason0** [comment]
:rina:

**Comment by Snow-dash** [comment]
可选自撤回不错，支持加上（

**Comment by OasisAkari** [comment]
可使用~enable server_disable_revoke来关闭自动撤回

注：此为临时解决方案，将来会有改动

**Comment by z0z0r4** [comment]
感谢

**Comment by z0z0r4** [comment]
![image](https://user-images.githubusercontent.com/78744121/155873971-9c4f01ea-8ce9-4cea-b75c-5cd85e0ffe28.png)
已经被s删除？那怎么关闭

**Comment by OasisAkari** [comment]
已修
