### ISSUE TITLE
小可疑似掉线

### ISSUE THREAD

**Issue by z0z0r4** [Teahouse-Studios/bot#143]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的问题，确定没有人提出过此问题/给出过其他解决方法

### 聊天平台

QQ群

### 用户ID

3531890582

### 群组ID

私聊小可

### 错误描述

执行任何消息无效，无回复

### 复现方法

同上

### 本应发生的结果

返回消息

### 截图

![URYNA3QOS3B6IFT25D %E1X](https://user-images.githubusercontent.com/78744121/148340974-930e1f0a-9f5f-494e-a3ec-19a7d8b4da4d.png)
如图，群聊一样

**Comment by OasisAkari** [comment]
go-cqhttp不知道为什么自己寄了
