### ISSUE TITLE
wiki模块加入手动审核查询条目

### ISSUE THREAD

**Issue by OasisAkari** [Teahouse-Studios/bot#15]
避免屏蔽词系统误判

**Comment by OasisAkari** [comment]
大概就是在发现屏蔽词的时候拦截并提醒发送的消息需要审核
然后向列表中的审核员账号发送消息来处理审核
若审核通过，则下一次使用相同命令时不会弹出拦截提示

**Comment by lakejason0** [comment]
真的吗

**Comment by OasisAkari** [comment]
然后rickroll特性可能会因此而被移除

**Comment by lakejason0** [comment]
你能保证相同命令总是有相同结果吗

**Comment by Dianliang233** [comment]
wiki 人人可编辑，有了人工审核机器人就更可能会被恶意利用

**Comment by OasisAkari** [comment]
那就保留rickroll，不提醒拦截（半恼
