### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by Nian233** [Teahouse-Studios/bot#151]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahou.se/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahou.se/privacy)、问谛居 [用户协议](https://doc.wd-ljt.com/policy/user/) 和 [隐私政策](https://doc.wd-ljt.com/policy/privacy/)
- [X] 我已事先添加当前机器人的账号 `2314163511` 为好友，且已发送群聊邀请/频道通行证至机器人。

### QQ群组类型

QQ群

### QQ号

1548649479

### QQ群

1065304668

### 备注

抱歉，群内管理员误操作禁言机器人，机器人自动退出，烦请通过审核_(:з」∠)_

**Comment by OasisAkari** [comment]
我们此次没有记录到对应操作的禁言时长，出于假定善意的目的，我们决定取消这次对操作者的封禁。

后续如再次违反服务条款，我们将不会再次同意请求
