### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Nian233** [Teahouse-Studios/bot#159]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的问题，确定没有人提出过此问题/给出过其他解决方法

### 聊天平台

QQ群

### 用户ID

1548649479

### 群组ID

1065304668

### 错误信息

__Nian__  
~server -p link.otakusever.top
发生错误：执行命令时发生错误，请报告机器人开发者：
sequence item 3: expected str instance, ErrorMessage found
错误汇报地址：https://github.com/Teahouse-Studios/bot/issues/new?assignees=OasisAkari&labels=bug&template=report_bug.yaml&title=%5BBUG%5D%3A+

### 错误描述

正在查询服务器人数信息，弹出了这个

### 复现方法

1.~server -p link.otakusever.top
2.报错

### 本应发生的结果

[JE]

在线玩家：0 / 233
游戏版本：Paper 1.18.1
link.otakusever.top:25565

**Comment by OasisAkari** [comment]
fixed
