### ISSUE TITLE
[BUG]: maimai_today

### ISSUE THREAD

**Issue by have19713** [Teahouse-Studios/bot#191]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的问题，确定没有人提出过此问题/给出过其他解决方法

### 聊天平台

Discord

### 用户ID

Scheld#4968

### 群组ID

https://discord.gg/axAkqbSQMT

### 错误信息

发生错误：执行命令时发生错误，请报告机器人开发者：
int() argument must be a string, a bytes-like object or a number, not 'Member'
错误汇报地址：https://github.com/Teahouse-Studios/bot/issues/new?assignees=OasisAkari&labels=bug&template=report_bug.yaml&title=%5BBUG%5D%3A+
GitHub

### 错误描述

执行“~maimai_today”
执行"~enable maimai_today"
执行"~maimai_today"
遇到错误

### 复现方法

执行“~maimai_today”
执行"~enable maimai_today"
执行"~maimai_today"
遇到错误

### 本应发生的结果

不知道

**Comment by OasisAkari** [comment]
已修。
