### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by SteveLoveReach** [Teahouse-Studios/bot#193]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahou.se/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahou.se/privacy)、问谛居 [用户协议](https://doc.wd-ljt.com/policy/user/) 和 [隐私政策](https://doc.wd-ljt.com/policy/privacy/)

### QQ群组类型

QQ群

### QQ号

2681461086

### QQ群

584390425

**Comment by OasisAkari** [comment]
邀请已发送
