### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by 2053628642** [Teahouse-Studios/bot#197]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的问题，确定没有人提出过此问题/给出过其他解决方法

### 聊天平台

QQ群

### 用户ID

2053628642

### 群组ID

345386596

### 错误信息

0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://zh.moegirl.org.cn/api.php?action=query&prop=info%7Cimageinfo%7Cextracts%7Cpageprops&inprop=url&iiprop=url&redirects=True&titles=%E6%AF%94%E5%AE%89%E5%8D%A1%E7%9C%9F%E7%90%86&ppprop=description%7Cdisplaytitle%7Cdisambiguation%7Cinfoboxes&explaintext=true&exsectionformat=plain&exchars=200&format=json')

### 错误描述

    无法搜索内容

### 复现方法

~wiki 比安卡 真理

### 本应发生的结果

搜索萌娘百科上比安卡真理的内容

**Comment by OasisAkari** [comment]
萌娘百科的问题 只能建议稍后再试 或者尝试直接访问萌娘百科
