### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by luo2f** [Teahouse-Studios/bot#198]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahou.se/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahou.se/privacy)、问谛居 [用户协议](https://doc.wd-ljt.com/policy/user/) 和 [隐私政策](https://doc.wd-ljt.com/policy/privacy/)

### QQ群组类型

QQ频道（beta）

### QQ号

1375880562

### QQ群

通行证，频道号：h1b1y94tc1

### 备注

没有就算了吧

**Comment by OasisAkari** [comment]
请给一个频道二维码或者加入链接，频道号无法搜索到频道
