### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by PCLxYNCat** [Teahouse-Studios/bot#216]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahou.se/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahou.se/privacy)、问谛居 [用户协议](https://doc.wd-ljt.com/policy/user/) 和 [隐私政策](https://doc.wd-ljt.com/policy/privacy/)

### QQ群组类型

QQ频道（beta）

### QQ号

2487215845

### QQ群

频道

**Comment by OasisAkari** [comment]
请发送一个有效的频道邀请链接

**Comment by PCLxYNCat** [comment]
https://qun.qq.com/qqweb/qunpro/share?_wv=3&_wwv=128&appChannel=share&inviteCode=12XcnZ&appChannel=share&businessType=9&from=246610&biz=ka#/pc
