### ISSUE TITLE
qaq

### ISSUE THREAD

**Issue by undlessusad** [Teahouse-Studios/bot#217]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahou.se/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahou.se/privacy)、问谛居 [用户协议](https://doc.wd-ljt.com/policy/user/) 和 [隐私政策](https://doc.wd-ljt.com/policy/privacy/)

### QQ群组类型

QQ群

### QQ号

2295352044

### QQ群

603454336

**Comment by OasisAkari** [comment]
无法找到相关群聊

**Comment by OasisAkari** [comment]
> 无法找到相关群聊

没有找到相关群聊，请检查群搜索功能是否打开，或群号是否提交错误
