### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by MedicineKing** [Teahouse-Studios/bot#219]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahou.se/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahou.se/privacy)、问谛居 [用户协议](https://doc.wd-ljt.com/policy/user/) 和 [隐私政策](https://doc.wd-ljt.com/policy/privacy/)

### QQ群组类型

QQ群

### QQ号

1580157505

### QQ群

1007994391

**Comment by OasisAkari** [comment]
没有找到相关群聊，请检查群搜索功能是否打开，或群号是否提交错误

**Comment by MedicineKing** [comment]
可以了，刚刚是搜索功能没开
