### ISSUE TITLE
加入新群

### ISSUE THREAD

**Issue by MSDNicrosoft** [Teahouse-Studios/bot#22]
**我已阅读并同意 Teahouse Studios [服务条款](https://teahou.se/terms/) 和 [隐私政策](https://teahou.se/privacy)、问谛居 [用户协议](https://doc.wd-ljt.com/policy/user/) 和 [隐私政策](https://doc.wd-ljt.com/policy/privacy/) 和 小可服务 [隐私协议](/policy/privacy/)。**

申请QQ号：3311835119

申请QQ群：594048732

备注：此群群主委托我本人弄的，但是由于群规要求，我暂时不能是管理员

**Comment by OasisAkari** [comment]
尝试直接添加机器人为好友后邀请入群

**Comment by MSDNicrosoft** [comment]
> 尝试直接添加机器人为好友后邀请入群

已添加好友且邀请过

**Comment by MSDNicrosoft** [comment]
> 尝试直接添加机器人为好友后邀请入群

请问能否允许有特例？

**Comment by OasisAkari** [comment]
稍后处理

**Comment by MSDNicrosoft** [comment]
> 稍后处理

非常感谢

**Comment by MSDNicrosoft** [comment]
> 稍后处理

请赋予 3311835119 的群内管理权限

**Comment by OasisAkari** [comment]
> 请赋予 3311835119 的群内管理权限

哦 我懂你意思了。不过你要求的暂时还没有实现 我先写一下

**Comment by OasisAkari** [comment]
已实现相关代码
请让群主/管理员在群内发送 ~admin_user add 3311835119来赋予权限

**Comment by MSDNicrosoft** [comment]
> 已实现相关代码
> 请让群主/管理员在群内发送 ~admin_user add 3311835119来赋予权限

好的，非常感谢
