### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by devilYD** [Teahouse-Studios/bot#226]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahou.se/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahou.se/privacy)、问谛居 [用户协议](https://doc.wd-ljt.com/policy/user/) 和 [隐私政策](https://doc.wd-ljt.com/policy/privacy/)

### QQ群组类型

QQ群

### QQ号

347231240

### QQ群

706283159

**Comment by OasisAkari** [comment]
无法找到指定群聊，请检查是否开启了群搜索功能

**Comment by devilYD** [comment]
> 
已修改设置，不好意思

**Comment by OasisAkari** [comment]
申请已发送
