### ISSUE TITLE
[NEW]: MinecraftBot

### ISSUE THREAD

**Issue by Redstone2337200** [Teahouse-Studios/bot#236]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahou.se/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahou.se/privacy)、问谛居 [用户协议](https://doc.wd-ljt.com/policy/user/) 和 [隐私政策](https://doc.wd-ljt.com/policy/privacy/)

### QQ群组类型

QQ群

### QQ号

3356168312

### QQ群

1094779099

### 备注

Minecraft

**Comment by OasisAkari** [comment]
因为不可抗力因素今天暂时没办法操作，抱歉
