### ISSUE TITLE
[NEW]: paper and

### ISSUE THREAD

**Issue by Xiaobeina1111** [Teahouse-Studios/bot#243]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)、问谛居 [用户协议](https://doc.wd-ljt.com/policy/user/) 和 [隐私政策](https://doc.wd-ljt.com/policy/privacy/)

### QQ群组类型

QQ群

### QQ号

825162264

### QQ群

922267511

### 备注

xc1580

**Comment by OasisAkari** [comment]
无法找到群聊，请检查是否开启群搜索
