### ISSUE TITLE
我的世界

### ISSUE THREAD

**Issue by XianYuFDK** [Teahouse-Studios/bot#245]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)、问谛居 [用户协议](https://doc.wd-ljt.com/policy/user/) 和 [隐私政策](https://doc.wd-ljt.com/policy/privacy/)

### QQ群组类型

QQ群

### QQ号

2112144907

### QQ群

859888776

**Comment by OasisAkari** [comment]
已发送申请，如未收到请检查过滤信息
