### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by D33274D7C6** [Teahouse-Studios/bot#250]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)、问谛居 [用户协议](https://doc.wd-ljt.com/policy/user/) 和 [隐私政策](https://doc.wd-ljt.com/policy/privacy/)

### QQ群组类型

QQ群

### QQ号

1762955435

### QQ群

群一581121996群二758627500

### 备注

某生电群解散了，无法白嫖机器人了，只好自己搞了。

**Comment by OasisAkari** [comment]
群一无法被搜索到，请检查入群设置

**Comment by D33274D7C6** [comment]
> 群一无法被搜索到，请检查入群设置

很抱歉，管理员失误，现在可以搜索了，能否重新提交一下呢？

**Comment by OasisAkari** [comment]
申请已发送
