### ISSUE TITLE
小可小可我的小可

### ISSUE THREAD

**Issue by assupr** [Teahouse-Studios/bot#256]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)、问谛居 [用户协议](https://doc.wd-ljt.com/policy/user/) 和 [隐私政策](https://doc.wd-ljt.com/policy/privacy/)

### QQ群组类型

QQ群

### QQ号

2713376976

### QQ群

657843232

### 备注

感谢各位大佬的付出！

**Comment by assupr** [comment]
为什么给关闭了啊？

**Comment by OasisAkari** [comment]
机器人已入群本issue即代表完成

**Comment by assupr** [comment]
那请问一下小可没有反应，我应该怎么做
