### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by Horizon-S** [Teahouse-Studios/bot#258]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)、问谛居 [用户协议](https://doc.wd-ljt.com/policy/user/) 和 [隐私政策](https://doc.wd-ljt.com/policy/privacy/)

### QQ群组类型

QQ群

### QQ号

3372523

### QQ群

204094959

### 备注

小可qwq

**Comment by OasisAkari** [comment]
无法搜索到群聊，请检查入群设置，或提供二维码等方式入群
