### ISSUE TITLE
user模块为wmf农场添加全域信息查询

### ISSUE THREAD

**Issue by lakejason0** [Teahouse-Studios/bot#38]
Wikimedia农场拥有额外的全域信息，目前机器人无法查询。部分用户告知这个功能可以方便他们查询，故在此提交请求。

相关的api入点会在确认后发布在这里。

见[mw:Extension:CentralAuth/API](https://www.mediawiki.org/wiki/Extension:CentralAuth/API)有关globaluserinfo的段落。

**Comment by Dianliang233** [comment]
https://www.mediawiki.org/w/api.php?action=query&format=json&meta=globaluserinfo&guiprop=editcount%7Cgroups%7Crights&guiuser=Dianliang233

**Comment by Dianliang233** [comment]
Implemented in fcb0fabc168ef2dedf15b8acfcc34e4fe5ee67d3
