### ISSUE TITLE
申请入群

### ISSUE THREAD

**Issue by Tonymti** [Teahouse-Studios/bot#4]
**申请QQ号：**2523176733

**申请QQ群：**977787821

**备注：**回复同意即可，望通过

**Comment by OasisAkari** [comment]
直接添加机器人好友后拉机器人入群没有反应吗？

**Comment by Tonymti** [comment]
> 直接添加机器人好友后拉机器人入群没有反应吗？

没有

**Comment by Tonymti** [comment]
> 直接添加机器人好友后拉机器人入群没有反应吗？

好了 谢谢

**Comment by OasisAkari** [comment]
好了。
