### ISSUE TITLE
特定 wiki sql error

### ISSUE THREAD

**Issue by Dianliang233** [Teahouse-Studios/bot#56]
(pymysql.err.ProgrammingError) (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\'adodoz\': "\'https://wiki.adodoz.cn/api.php\'", \'moe\': "\'https://zh.moegirl.org.cn\' at line 3')
[SQL: SELECT `module_wiki_WikiInfo`.`apiLink` AS `module_wiki_WikiInfo_apiLink`, `module_wiki_WikiInfo`.`siteInfo` AS `module_wiki_WikiInfo_siteInfo`, `module_wiki_WikiInfo`.timestamp AS `module_wiki_WikiInfo_timestamp` 
FROM `module_wiki_WikiInfo` 
WHERE `module_wiki_WikiInfo`.`apiLink` = %(apiLink_1)s 
 LIMIT %(param_1)s]
[parameters: {'apiLink_1': {'adodoz': 'https://wiki.adodoz.cn/api.php', 'moe': 'https://zh.moegirl.org.cn/api.php', 'gphelpzh': 'https://help-zh.gamepedia.com/api.php', 'wzh': ' ... (1370 characters truncated) ... es.top:233/api.php', 'aph': 'https://hetalia.fandom.com/api.php', 'trw': 'https://terraria.fandom.com/api.php', 'ftb': 'https://ftb.fandom.com/wiki/'}, 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/13/f405)

**Comment by OasisAkari** [comment]
已查明原因：列数据类型错误，mysql下应为LONGTEXT而非Text类型
