### ISSUE TITLE
重写wikilib的解析方式

### ISSUE THREAD

**Issue by OasisAkari** [Teahouse-Studios/bot#63]

**Comment by OasisAkari** [comment]
我自己写的代码给我自己看蒙了，妈了

由于后续扩增内容的问题，wiki模块的核心部分需要全部重写

**Comment by OasisAkari** [comment]
在考虑要不要放弃并发支持（缩）

写起来过于烧脑

**Comment by XxLittleCxX** [comment]
这玩意要啥并发，不本来就应该是并发的吗

**Comment by OasisAkari** [comment]
> 这玩意要啥并发，不本来就应该是并发的吗

.....（大概就是被一堆复杂的使用情景搞的不会说话了）
