### ISSUE TITLE
无法抓简介

### ISSUE THREAD

**Issue by HornCopper** [Teahouse-Studios/bot#68]
**问题描述：**小可没有获取到简介

**复现方法：**<del>重复对照实验（？）</del>发送~wiki mcrwiki:Avaritia

**本应发生的结果：**链接+简介

**截图：**
![6942969d661c0e22](https://user-images.githubusercontent.com/68726147/134532184-ceb62b81-96f6-4a3b-aa01-640f6f08a398.png)

**备注：**MCR Wiki:https://wiki.mcresources.top:233（MediaWiki 1.36.1 TextExtract已启用）

**Comment by OasisAkari** [comment]
尊敬的用户，您好：

关于您的问题，这边已经了解到。经查，是您服务器的api没有正确传回数据：
https://wiki.mcresources.top:233/api.php?action=query&prop=info|pageprops|extracts&ppprop=description|displaytitle|disambiguation|infoboxes&explaintext=True&exsectionformat=plain&titles=Thaumcraft
![image](https://user-images.githubusercontent.com/31803608/134533712-d8d44c1a-2e56-40d1-bacb-5bf340a01d4b.png)

解决方案：
还望您自查一下，感谢。

如果问题已解决欢迎您给出评价，5星为满意。您的反馈能让我们做得更好，感谢您对小可的支持！
如果问题尚未解决，您可以继续在本工单中留言，我们会为您持续跟进。
如果您有其他新的问题，欢迎提交新的工单联系我们。

**Comment by HornCopper** [comment]
下次一定修，谢谢你的答复（
