### ISSUE TITLE
ptt 模块未判断用户输入

### ISSUE THREAD

**Issue by gnnoh** [Teahouse-Studios/bot#70]
**问题描述：** ptt 模块未判断用户输入

**复现方法：** <code>~ptt -1</code> <code>~ptt 1.234</code> <code>~ptt 114514</code>

**本应发生的结果：** 小可拒绝回复 Potential 图片并发送相关提示

**截图：**
![114514](https://user-images.githubusercontent.com/48518325/135304091-bb59c770-1709-4f96-840a-a5a6b77d658d.png)

**备注：** 改[文档](https://bot.teahou.se/wiki/ptt)还是改代码（

**Comment by XxLittleCxX** [comment]
这种情况推荐pr

**Comment by gnnoh** [comment]
> 
> 
> 这种情况推荐pr

那未来可期

**Comment by OasisAkari** [comment]
明天有空了修

**Comment by OasisAkari** [comment]
顺便把arcaea最近模块撸出来
